# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Arch Linux bump package versions action
description: GitHub Action to bump versions of nepositories containing PKGBUILDs.
author: callmetango

inputs:
  name-pattern:
    description: The pattern of the package names to consider
    type: string
  old-version:
    description: The old version to bump
    type: string
  new-version:
    description: The new version to bump to
    type: string

  # repository filters
  owner:
    description: The owner of the GitHub repositories. (Defaults to the owner of the current repository)

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_NAME_PATTERN: ${{ inputs.name-pattern }}
    INPUT_OLD_VERSION: ${{ inputs.old-version }}
    INPUT_NEW_VERSION: ${{ inputs.new-version }}
    INPUT_OWNER: ${{ inputs.owner }}
