name: Arch Linux bump package version action
description: GitHub Action to bump the version of a PKGBUILD.
author: callmetango

inputs:
  path:
    description: Location for this action to run
    type: string
  pkgver:
    description: The new version to bump to
    type: string
  pkgrel: 
    description: The pkgrel to use
    type: string
  old-version:
    description: |
      The old version. If the package version does not match this pattern the action will fail.
      Not implemented
    type: string
  srcinfo:
    description: Generate new .SRCINFO
    type: choice
    options:
      - auto
      - true
      - false
    default: auto
  updpkgsums:
    description: Update the checksums of the PKGBUILD
    type: boolean
    default: true
  namcap:
    description: Set to true to validate the PKGBUILD with namcap
    type: boolean
  namcap-opts:
    description: Options to pass to namcap
    type: string
    default: '-i'

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_PATH: ${{ inputs.path }}
    INPUT_PKGVER: ${{ inputs.pkgver }}
    INPUT_PKGREL: ${{ inputs.pkgrel }}
    INPUT_OLD_VERSION: ${{ inputs.old-version }}
    INPUT_SCRINFO: ${{ inputs.srcinfo }}
    INPUT_UPDPKGSUMS: ${{ inputs.updpkgsums }}
    INPUT_NAMCAP: ${{ inputs.namcap }}
    INPUT_NAMCAP_OPTS: ${{ inputs.namcap-opts }}
